---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

```

```{css}

```

## What's going on with this data?

You need to change the contents of this Rmd! Replace the R code and markdown give below in this template document.

```{r}
library(tidyverse)

#Load the CSV form,Using the read_csv() function to read the data

Logged_data <- read_csv ("https://docs.google.com/spreadsheets/d/e/2PACX-1vSqmNsKYk1tMRtLGm7GnGLojZjwW9nCLYFmr2DA3MvlzBT6G-bhwo1TOtyQwr6MsO40BNOCKxhI9qG0/pub?output=csv")


#Rename the data name
Latest_data<-Logged_data%>%
  rename(date=1,
         Outcome=2,
         Total_amount_spent=3,
         Whether_or_not_spending_has_taken_place=4)%>%
  select(date,,Outcome,Total_amount_spent,Whether_or_not_spending_has_taken_place)

#Make sure the money is numeric

Latest_data <- Latest_data %>%
  mutate(Total_amount_spent = as.numeric(Total_amount_spent))

#Average of total spent of a day

average<-mean(Latest_data$Total_amount_spent)
print(paste("average:",average))


#Sum of total spent of each day

Total <- sum(Latest_data$Total_amount_spent, na.rm = TRUE)
print(paste("Total:", Total))


#bar1 of Total Amount Spent Of Each Day
Latest_data %>%
  slice(1:50) %>%
  ggplot(aes(x = date, y = Total_amount_spent, fill = date)) +
  geom_bar(stat = "identity") +
  labs(x = "Date", y = "Total Amount Spent", title = "Total Amount Spent Of Each Day") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 30, hjust = 1))


#bar2 of Average spent of each day
Latest_data%>%
  slice(1: 50) %>%  #scale
  ggplot() +
  geom_bar(aes(x = date, fill = average))+
  labs(x = "Date", y = "Average spent", title = "Average spent of each day") +
  theme_minimal() + #edit the content of form name
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) #change the position of date letter



```
